In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import torch
import os

In [2]:
train = pd.read_csv('/kaggle/input/titanic/train.csv')
test = pd.read_csv('/kaggle/input/titanic/test.csv')
gender_submission = pd.read_csv('/kaggle/input/titanic/gender_submission.csv')

train.shape, test.shape, gender_submission.shape, train.columns

((891, 12),
 (418, 11),
 (418, 2),
 Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
        'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
       dtype='object'))

In [3]:
features = ["Pclass","Name", "Sex", "Age","SibSp", "Parch", "Ticket", "Fare", "Cabin", "Embarked"]
train_y = train["Survived"]
train_X = train[features]
test_X = test[features]
print(train_X.describe())
train_X.head()

           Pclass         Age       SibSp       Parch        Fare
count  891.000000  714.000000  891.000000  891.000000  891.000000
mean     2.308642   29.699118    0.523008    0.381594   32.204208
std      0.836071   14.526497    1.102743    0.806057   49.693429
min      1.000000    0.420000    0.000000    0.000000    0.000000
25%      2.000000   20.125000    0.000000    0.000000    7.910400
50%      3.000000   28.000000    0.000000    0.000000   14.454200
75%      3.000000   38.000000    1.000000    0.000000   31.000000
max      3.000000   80.000000    8.000000    6.000000  512.329200

,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
def preprocess(df):
    df = df.copy()
    def title(x):
        return x.split(" ")[1]
    def ticket_item(x):
        items = x.split(" ")
        if len(items) == 1:
            return "NONE"
        return items[0]
      
    df["Title"] = df["Name"].apply(title)
    df["Ticket_item"] = df["Ticket"].apply(ticket_item)
    df["Age"] = df["Age"].fillna(train_X["Age"].mean())
    df["Cabin"] = df["Cabin"].fillna("NONE")
    df["Embarked"] = df["Embarked"].fillna("NONE")
    df["Has_cabin"] = (df["Cabin"] != "NONE").astype(int)
    
    df.drop(columns="Cabin", inplace=True)
    df.drop(columns='Name', inplace=True)
    df.drop(columns='Ticket', inplace=True)
    return df

processed_train_X = preprocess(train_X)
processed_test_X = preprocess(test_X)

processed_train_X.head()

,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Title,Ticket_item,Has_cabin
0,3,male,22.0,1,0,7.2500,S,Mr.,A/5,0
1,1,female,38.0,1,0,71.2833,C,Mrs.,PC,1
2,3,female,26.0,0,0,7.9250,S,Miss.,STON/O2.,0
3,1,female,35.0,1,0,53.1000,S,Mrs.,NONE,1
4,3,male,35.0,0,0,8.0500,S,Mr.,NONE,0